inherit_gem:
  rubocop_defaults: .rubocop.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - .pryrc

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Max: 10

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
