inherit_gem:
  rubocop_defaults: .rubocop.yml

inherit_mode:
  merge:
    - Exclude
    - IgnoredMethods

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - .pryrc

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/bundler/dependencies/cli_spec.rb

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - and
    - method_option
