inherit_from: .rubocop_todo.yml

require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude
    - IgnoredMethods

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions:
    rubocop-rake: false
  Exclude:
    - .pryrc

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Naming/FileName:
  Exclude:
    - lib/bundler-dependencies.rb

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - spec/bundler/dependencies/cli_spec.rb

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/NotToNot:
  EnforcedStyle: to_not

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - and
    - method_option
